initdbScripts:
  user.sql: |
    CREATE USER 'weops'@'%' IDENTIFIED BY 'Weops123!';
    GRANT PROCESS, SELECT ON *.* TO 'weops'@'%';
    GRANT REPLICATION CLIENT ON *.* TO 'weops'@'%';
    GRANT REPLICATION SLAVE MONITOR ON *.* TO 'weops'@'%';
    GRANT  REPLICA MONITOR ON *.* TO 'weops'@'%';

auth:
  rootPassword: Weops123!

primary:
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 300m
      memory: 800Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false

secondary:
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 300m
      memory: 800Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
